### ISSUE TITLE
Can you help to link against it?

### ISSUE THREAD

**Issue by exebook** [changloong/libuv#1]
I tried:

ldc2 hello.d -luv
import libuv;

Tried -I= various dirs

But nothing works, I am a noob to D.

**Comment by exebook** [comment]
Assuming you did git clonegit@github.com:changloong/libuv.git in current dir.

Compile:

ldc2 hello.d -I=libuv/deimos/libuv/ -I=libuv/ -L=-luv
The source:

import uv;
import core.memory;
import std.stdio;

int main(){
    uv_loop_t *loop = new uv_loop_t;
    uv_loop_init(loop);

    printf("Now quitting.\n");
    uv_run(loop, uv_run_mode.UV_RUN_DEFAULT);

    uv_loop_close(loop);
    return 0;
}
Hope it helps someone to get started with using C libs in D.

**Comment by changloong** [comment]
If you are using it with debian: `apt-get install libuv0.10-dev`,  then you can use it with ldc2.  

you can also use it with dub.json
