### ISSUE TITLE
Are you working to create a d-style wrapper for it?

### ISSUE THREAD

**Issue by exebook** [changloong/libuv#3]
I am looking to write some wrapper to make it easier to use D-style, with delegates for callbacks, strings for data writes and reads. Are you interested to work in that area?

**Comment by changloong** [comment]
Hi @exebook ,

Like https://github.com/s-ludwig/libevent used in Vibed,  I feel it is more easy & clean to use with pure C interface in D.  I am current use libuv with my GC-Free network framework (not open source yet),  please feel free to made your own D wrapper.
